---

- name: Create a virtual machine and install tools
  hosts: all
  vars_files:
    - env_vars/vagrant.yml
  roles:
    - { role: common, sudo: yes }
    - { role: java, sudo: yes }
    - { role: python, sudo: yes }
    - { role: scala, sudo: yes }
    - { role: sbt, sudo: yes }